### PR TITLE
Update search

### PR DESCRIPTION
**Pull request by gep13**
## Description Of Changes

When a package search resource is returned, it should first check to see
if the feed that is being accessed has the capabilities to perform the
search.  If this is not done, saerches can be emitted against a feed
which will fail.  A similar check is performed when using a listResource
so this commit does something very similar for a searchResource.  Within
this commit, a NullLogger is used, which isn't ideal, but without
additional work, and refactoring, this has been deemed as ok for now. A
follow up issue will be created to try to remove the usage of this
NullLogger.

In addition to being able to list out the packages from a search on a
feed, it is also necessary to know the numbers of packages that are
available, so that correct paging can be applied in applications like
Chocolatey GUI.  This commit add a SearchCountAsync method with an
implementation for for v2 and v3 feeds. It is believed that the v3 feed
will need additional work, but this implementation is aimed at getting
things working in Chocolatey GUI, when using v2 feeds, so additional
work will be done in follow up commits.

When searching for packages from both Chocolatey CLI and Chocolatey GUI
it is possible to provide a sort order in the form of DownloadCount. This
functionality was missing from the NuGet.Client libraries, so this commit
adds this back in, for V2 feeds.  It is now possible to order by both Id
and DownloadCount, and the correct oData query will be emitted.

## Motivation and Context

We need searching/paging in Chocolatey GUI to work in the new version, as it does in the current version

## Testing

Testing of these changes needs to be done in conjunction with changes in Chocolatey CLI, so the testing steps will be added to the corresponding PR there, once everything is ready.

### Operating Systems Testing

- Windows 10/11

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added. (Tests has not been updated, as I do not know which are affected by localization and which may have been affected by the update, tests will instead be enabled or added to Chocolatey CLI E2E)
* [ ] All new and existing tests passed? (More tests has been made English only since the last update, unable to verify whether they succeed or not)
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

- #9  
- https://github.com/chocolatey/choco/issues/508
- https://app.clickup.com/t/20540031/PROJ-465

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
Not taken this for a test run yet, will do that as part of the PR into Chocolatey CLI. However, the changes LGTM

**Comment by gep13** [comment]
@AdmiringWorm let me know when you have taken this for a spin.  I have pushed up the changes that I mentioned still need to be done, i.e. updating the commit with `Co-Authoredby`

**Comment by AdmiringWorm** [comment]
@gep13 I have taken it for a spin with the choco PR. I just never had the chance to update you on that.

Everything looks good to me

**Comment by gep13** [comment]
@AdmiringWorm thank you for taking a look at this!

**Comment by 213768mlg** [comment]
> ## Description Of Changes
> When a package search resource is returned, it should first check to see if the feed that is being accessed has the capabilities to perform the search. If this is not done, saerches can be emitted against a feed which will fail. A similar check is performed when using a listResource so this commit does something very similar for a searchResource. Within this commit, a NullLogger is used, which isn't ideal, but without additional work, and refactoring, this has been deemed as ok for now. A follow up issue will be created to try to remove the usage of this NullLogger.
> 
> In addition to being able to list out the packages from a search on a feed, it is also necessary to know the numbers of packages that are available, so that correct paging can be applied in applications like Chocolatey GUI. This commit add a SearchCountAsync method with an implementation for for v2 and v3 feeds. It is believed that the v3 feed will need additional work, but this implementation is aimed at getting things working in Chocolatey GUI, when using v2 feeds, so additional work will be done in follow up commits.
> 
> When searching for packages from both Chocolatey CLI and Chocolatey GUI it is possible to provide a sort order in the form of DownloadCount. This functionality was missing from the NuGet.Client libraries, so this commit adds this back in, for V2 feeds. It is now possible to order by both Id and DownloadCount, and the correct oData query will be emitted.
> 
> ## Motivation and Context
> We need searching/paging in Chocolatey GUI to work in the new version, as it does in the current version
> 
> ## Testing
> Testing of these changes needs to be done in conjunction with changes in Chocolatey CLI, so the testing steps will be added to the corresponding PR there, once everything is ready.
> 
> ### Operating Systems Testing
> * Windows 10/11
> 
> ## Change Types Made
> * [ ]  Bug fix (non-breaking change).
> * [x]  Feature / Enhancement (non-breaking change).
> * [ ]  Breaking change (fix or feature that could cause existing functionality to change).
> * [ ]  Documentation changes.
> * [ ]  PowerShell code changes.
> 
> ## Change Checklist
> * [ ]  Requires a change to the documentation.
> * [ ]  Documentation has been updated.
> * [ ]  Tests to cover my changes, have been added. (Tests has not been updated, as I do not know which are affected by localization and which may have been affected by the update, tests will instead be enabled or added to Chocolatey CLI E2E)
> * [ ]  All new and existing tests passed? (More tests has been made English only since the last update, unable to verify whether they succeed or not)
> * [ ]  PowerShell code changes: PowerShell v2 compatibility checked?
> 
> ## Related Issue
> * [Add Chocolatey specific functionality to NuGet.Client assemblies #9](https://github.com/chocolatey/NuGet.Client/issues/9)
> * [Upgrade to target version 3.1.0 of Chocolatey.NuGet.Client assemblies choco#508](https://github.com/chocolatey/choco/issues/508)
> * https://app.clickup.com/t/20540031/PROJ-465

**Pull request merged**
