### PR TITLE
(#9) Add missing elements to search metadata

### PR DESCRIPTION
**Pull request by gep13**
## Description Of Changes

Add more Chocolatey specific server side information into the NuGet.Client assemblies, so that this information can be used/displayed from Chocolatey.

**NOTE:** This will need to be used in conjunction with a PR: https://github.com/chocolatey/choco/pull/2988

## Motivation and Context

When the first work was done to provide Chocolatey specific server related information from the NuGet.Client libraries, it concentrated on the following properties:

PackageHash, PackageHashAlgorithm, PackageSize, VersionDownloadCount, IsApproved, PackageStatus, PackageSubmittedStatus, PackageTestResultStatus, PackageTestResultStatusDate, PackageValidationResultStatus, PackageValidationResultDate, PackageCleanupResultDate, PackageReviewedDate, PackageApprovedDate, PackageReviewer, IsDownloadCacheAvailable, DownloadCacheDate, DownloadCache

This can be seen in this commit:

https://github.com/NuGet/NuGet.Client/commit/3c891b18af767149dcdc3df65e7cf1e515ba7d08

During testing, it was found that at least the ReleaseNotes property needed to be included, since this was missing in the output from the choco info command.  On further conversations, it was decided that a number of other properties should be added into the NuGet.Client libraries so that all meaningful information would be included.  These properties are:

- IsLatestVersion
- IsAbsoluteLatestVersion
- IsPrerelease
- ReleaseNotes
- ProjectSourceUrl
- PackageSourceUrl
- DocsUrl
- MailingListUrl
- BugTrackerUrl
- DownloadCacheStatus
- PackageScanStatus
- PackageScanResultDate
- PackageScanFlagResult

## Testing

- Built the NuGet.Client project in debug mode using the following command `.\build.ps1 -CI -SkipUnitTest -BuildNumber 108 -ReleaseLabel alpha -BuildDate (Get-Date -Format "yyyyMMdd") -Configuration "debug"`
- Copied the `Chocolatey.NuGet.Protocol.dll` and `Chocolatey.NuGet.Protocol.pdb` files into the `src\chocolatey.console\bin\Debug` folder
- Checkout the code in this [PR](https://github.com/chocolatey/choco/pull/2988) to update chocolatey/choco with required changes
- Ran Chocolatey from within Visual Studio using `info git.install` as debug parameters
- Ran the same command from Chocolatey 1.2.1
- Compared the output from both commands to ensure that all required output was included (It was noted that the `Package url` works when running out of Visual Studio, but not from 1.2.1).
- The package used in the above test doesn't actually include any Release Notes, since there aren't any in the package, however, run again for `choco info chocolatey` to see the release notes being included

### Operating Systems Testing

- Windows 10 22H2

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [x] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

- https://github.com/chocolatey/NuGet.Client/issues/9
- https://github.com/chocolatey/choco/issues/508
- https://app.clickup.com/t/20540031/PROJ-459

### CODE REVIEW

**Comment by TheCakeIsNaOH** [comment]
These added properties can be split into three groups. 

The first is properties that were added to CCR and into NuGet.Core:
ReleaseNotes
ProjectSourceUrl
PackageSourceUrl
DocsUrl
MailingListUrl
BugTrackerUrl

The second is properties that were added to CCR, but not added into NuGet.Core (I think they were mostly added after the major NuGet.Core changes and so were missed).
DownloadCacheStatus
PackageScanStatus
PackageScanResultDate
PackageScanFlagResult

The third is properties that were available in upstream NuGet.Core, but were removed in NuGet SDK, because v3 feeds do not support them.
IsLatestVersion
IsAbsoluteLatestVersion
IsPrerelease

I have no issues with the first two groups being added. I missed the first group, as they were added in a NuGet.Core commit that I thought was for local packages only. 

However, for the third group, I'm not sure adding them is the best option. In general, if they would be used anywhere, the assumption would be that they would be always available from remote sources, because previously only v2 feeds were available. Now any usages of them has to be careful to either check what feed type the result came from and add a fallback for v3 feeds, or otherwise check if they were set and add a fallback if they were not set.

**Comment by gep13** [comment]
@TheCakeIsNaOH I spoke with @AdmiringWorm this morning about this, and we have come to an agreement on how we should proceed with this.

We won't add those properties onto the interface, but we will add them to the specific implementation for the v2 feed, that way, those properties can still be used down the line if/when required.

@AdmiringWorm this should be ready for another review.

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@gep13 great work, thanks for getting these added

**Pull request merged**
